### PR TITLE
Support for Null safety and API 30

### PR DESCRIPTION
**Pull request by bluntmess**
Please have a look at it and if possible upload it to pub.dev.
Thank you.

### CODE REVIEW

**Comment by lbaey** [comment]
Hello
Thank you for this ! 👍 
I would merge right away but I have concerns about the singlePageFileName output numerotation, as changing it would maybe break our app using this plugin. Could you please revert to the old way of naming and maybe add some sort of outFileNameTemplate argument in another PR ?

**Comment by bluntmess** [comment]
Hey, thanks for notifying me about that. I have reverted the changes.

**Comment by bluntmess** [comment]
Hello @lbaey, any update over this.

**Comment by lbaey** [comment]
Thx ! 👍

**Pull request merged**
